runtime: python37
#api_version: 1
#threadsafe: true
# entrypoint: gunicorn -b :$PORT main:app
entrypoint: gunicorn -b :$PORT -b :2222 main:app


#entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 2    #internal service error
#entrypoint: uwsgi --socket 127.0.0.1:8080 --protocol=http -w wsgi:app            #keeps loading... for a long time

# instance_class: F2

# # [START handlers]
# handlers:
# - url: /static
#   static_dir: static
#   secure: always
# - url: /.*
#   script: auto #main.app
#   secure: always
#   redirect_http_response_code: 301
# [END handlers]

#[START env]
#env_variables:
    #BUCKET_NAME: my_poop_bucket	
    #GCP_PROJECT: serious-curve-263420
    #SESSION_SECRET_KEY: Q09cHpXDmn8h7ybVd0Z8EG5wAZ1kSTgIpiwcCg3X
    #GOOGLE_CLOUD_PROJECT: my_poop_bucket
    #SESSION_SECRET_KEY: 9cd3658f3605f6884a54c01b93eb7b8707f0a09a

#[END env]